module.exports = [
    {
      title: "Sample Data - Monday Running",
      minutes: 90,
      distance: 2,
      instensity: "light",
      location: "Santiago de Chile",
      notes: "Just a chill run, my knee has been hurting and I prefer to take care of it. ",
    },
    {
      title: "Sample Data - Tuesday Running",
      minutes: 90,
      distance: 25,
      instensity: "moderate",
      location: "Santiago de Chile",
      notes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nec facilisis velit. Mauris vulputate suscipit erat viverra vestibulum. Etiam sollicitudin.",
    },
    {
      title: "Sample Data - Late Running",
      minutes: 90,
      distance: 100,
      instensity: "light",
      location: "Santiago de Chile",
      notes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nec facilisis velit. Mauris vulputate suscipit erat viverra vestibulum. Etiam sollicitudin.",
    },
    {
      title: "Sample Data - Jogging",
      minutes: 24,
      distance: 5,
      instensity: "light",
      location: "Santiago de Chile",
      notes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nec facilisis velit. Mauris vulputate suscipit erat viverra vestibulum. Etiam sollicitudin.",
    },
    {
      title: "Sample Data - Running with Sara",
      minutes: 36,
      distance: 11,
      instensity: "light",
      location: "Santiago de Chile",
      notes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nec facilisis velit. Mauris vulputate suscipit erat viverra vestibulum. Etiam sollicitudin.",
    },
    {
      title: "Sample Data - 20 Miles training",
      minutes: 54,
      distance: 8,
      instensity: "intense",
      location: "Santiago de Chile",
      notes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In nec facilisis velit. Mauris vulputate suscipit erat viverra vestibulum. Etiam sollicitudin.",
    },
  ]