module.exports = [
    {
      title: "Sample Data - Monday Running",
      minutes: 90,
      distance: 10,
      instensity: "light",
      location: "Santiago de Chile",
      notes: "Just a chill run",
    },
    {
      title: "Sample Data - Tuesday Running",
      minutes: 90,
      distance: 25,
      instensity: "moderate",
      location: "Santiago de Chile",
      notes: "I did 25 miles without stopping!",
    },
    {
      title: "Sample Data - Late Running",
      minutes: 90,
      distance: 10,
      instensity: "light",
      location: "Santiago de Chile",
      notes: "The sun was amazing",
    },
    {
      title: "Sample Data - Jogging",
      minutes: 30,
      distance: 5,
      instensity: "light",
      location: "Santiago de Chile",
      notes: "It was too cold",
    },
    {
      title: "Sample Data - Running with Sara",
      minutes: 90,
      distance: 10,
      instensity: "light",
      location: "Santiago de Chile",
      notes: "20 miles",
    },
    {
      title: "Sample Data - 20 Miles training",
      minutes: 90,
      distance: 10,
      instensity: "intense",
      location: "Santiago de Chile",
      notes: "My anckle hurts a little",
    },
  ]